FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir redis==5.2.0

COPY app ./app

RUN groupadd --system app --gid 10001 \
 && useradd  --system app --uid 10001 --gid 10001 \
 && chown -R app:app /app

USER 10001:10001

CMD ["python", "-m", "app.worker"]
